name: React CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-versions: [17.x]
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn run build
      - run: yarn test